#!/usr/bin/env bash
# Exit on error
# exit when any command fails
set -e
set -o pipefail

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' ERR

msbuild=`find $WINDIR/Microsoft.NET/Framework/v3.5 -name "MSBuild.exe"`

$msbuild Assembly-CSharp/Assembly-CSharp.csproj