#!/usr/bin/env bash
# Exit on error
# exit when any command fails
set -e
set -o pipefail

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' ERR

preCommitFile="./.git/hooks/pre-commit"
preCommitHook="./precommit-hook"

echo "Adding pre-commit hook"
cat ${preCommitHook} > ${preCommitFile}

echo "Marking as executable"
chmod u+x ${preCommitFile}

echo "Installing dotnet-format"
dotnet tool install -g dotnet-format || exit 0